"""Request ID middleware — reads X-Request-ID from the incoming request
(generated by Nike gateway) and stores it in a ContextVar for logging and
forwarding to downstream services.

If the header is missing (direct access, tests), generates a UUID v4.
"""
from __future__ import annotations

import logging
import uuid
from contextvars import ContextVar

from starlette.types import ASGIApp, Receive, Scope, Send

_request_id: ContextVar[str] = ContextVar("request_id", default="")


def get_request_id() -> str:
    """Return the request ID for the current async context, or empty string."""
    return _request_id.get()


class RequestIdMiddleware:
    """ASGI middleware that extracts X-Request-ID from the request headers
    and stores it in a ContextVar. Also sets it in the response headers."""

    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] not in ("http", "websocket"):
            await self.app(scope, receive, send)
            return

        headers = dict(scope.get("headers", []))
        rid = headers.get(b"x-request-id", b"").decode("utf-8", errors="ignore")
        if not rid or len(rid) > 64:
            rid = str(uuid.uuid4())

        _request_id.set(rid)

        async def send_with_rid(message: dict) -> None:
            if message["type"] == "http.response.start":
                response_headers = message.get("headers", [])
                response_headers.append((b"x-request-id", rid.encode("utf-8")))
                message["headers"] = response_headers
            await send(message)

        await self.app(scope, receive, send_with_rid)


class RequestIdLogFilter(logging.Filter):
    """Logging filter that injects the current request_id into every log record."""

    def filter(self, record: logging.LogRecord) -> bool:
        record.request_id = get_request_id() or "-"
        return True
