# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app import helios_pb2 as helios__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in helios_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HeliosServiceStub(object):
    """HeliosService defines the gRPC service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Calculate = channel.unary_unary(
                '/helios.HeliosService/Calculate',
                request_serializer=helios__pb2.CalculationRequest.SerializeToString,
                response_deserializer=helios__pb2.CalculationCompleted.FromString,
                _registered_method=True)
        self.GetOHLCV = channel.unary_unary(
                '/helios.HeliosService/GetOHLCV',
                request_serializer=helios__pb2.GetOHLCVRequest.SerializeToString,
                response_deserializer=helios__pb2.GetOHLCVResponse.FromString,
                _registered_method=True)
        self.GetFeatures = channel.unary_unary(
                '/helios.HeliosService/GetFeatures',
                request_serializer=helios__pb2.GetFeaturesRequest.SerializeToString,
                response_deserializer=helios__pb2.GetFeaturesResponse.FromString,
                _registered_method=True)
        self.GetIndicators = channel.unary_unary(
                '/helios.HeliosService/GetIndicators',
                request_serializer=helios__pb2.GetIndicatorsRequest.SerializeToString,
                response_deserializer=helios__pb2.GetIndicatorsResponse.FromString,
                _registered_method=True)
        self.StreamOHLCV = channel.unary_stream(
                '/helios.HeliosService/StreamOHLCV',
                request_serializer=helios__pb2.StreamOHLCVRequest.SerializeToString,
                response_deserializer=helios__pb2.OHLCV.FromString,
                _registered_method=True)
        self.StreamFeatures = channel.unary_stream(
                '/helios.HeliosService/StreamFeatures',
                request_serializer=helios__pb2.StreamFeaturesRequest.SerializeToString,
                response_deserializer=helios__pb2.Feature.FromString,
                _registered_method=True)
        self.StreamIndicators = channel.unary_stream(
                '/helios.HeliosService/StreamIndicators',
                request_serializer=helios__pb2.StreamIndicatorsRequest.SerializeToString,
                response_deserializer=helios__pb2.Indicator.FromString,
                _registered_method=True)
        self.SubscribeToSymbols = channel.stream_stream(
                '/helios.HeliosService/SubscribeToSymbols',
                request_serializer=helios__pb2.SubscriptionRequest.SerializeToString,
                response_deserializer=helios__pb2.SubscriptionResponse.FromString,
                _registered_method=True)


class HeliosServiceServicer(object):
    """HeliosService defines the gRPC service
    """

    def Calculate(self, request, context):
        """Calculator Service RPC (from API.md)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOHLCV(self, request, context):
        """Unary RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFeatures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIndicators(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamOHLCV(self, request, context):
        """Server Streaming RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFeatures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamIndicators(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeToSymbols(self, request_iterator, context):
        """Bidirectional Streaming RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HeliosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Calculate': grpc.unary_unary_rpc_method_handler(
                    servicer.Calculate,
                    request_deserializer=helios__pb2.CalculationRequest.FromString,
                    response_serializer=helios__pb2.CalculationCompleted.SerializeToString,
            ),
            'GetOHLCV': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOHLCV,
                    request_deserializer=helios__pb2.GetOHLCVRequest.FromString,
                    response_serializer=helios__pb2.GetOHLCVResponse.SerializeToString,
            ),
            'GetFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFeatures,
                    request_deserializer=helios__pb2.GetFeaturesRequest.FromString,
                    response_serializer=helios__pb2.GetFeaturesResponse.SerializeToString,
            ),
            'GetIndicators': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIndicators,
                    request_deserializer=helios__pb2.GetIndicatorsRequest.FromString,
                    response_serializer=helios__pb2.GetIndicatorsResponse.SerializeToString,
            ),
            'StreamOHLCV': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamOHLCV,
                    request_deserializer=helios__pb2.StreamOHLCVRequest.FromString,
                    response_serializer=helios__pb2.OHLCV.SerializeToString,
            ),
            'StreamFeatures': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFeatures,
                    request_deserializer=helios__pb2.StreamFeaturesRequest.FromString,
                    response_serializer=helios__pb2.Feature.SerializeToString,
            ),
            'StreamIndicators': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamIndicators,
                    request_deserializer=helios__pb2.StreamIndicatorsRequest.FromString,
                    response_serializer=helios__pb2.Indicator.SerializeToString,
            ),
            'SubscribeToSymbols': grpc.stream_stream_rpc_method_handler(
                    servicer.SubscribeToSymbols,
                    request_deserializer=helios__pb2.SubscriptionRequest.FromString,
                    response_serializer=helios__pb2.SubscriptionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'helios.HeliosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('helios.HeliosService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HeliosService(object):
    """HeliosService defines the gRPC service
    """

    @staticmethod
    def Calculate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helios.HeliosService/Calculate',
            helios__pb2.CalculationRequest.SerializeToString,
            helios__pb2.CalculationCompleted.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOHLCV(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helios.HeliosService/GetOHLCV',
            helios__pb2.GetOHLCVRequest.SerializeToString,
            helios__pb2.GetOHLCVResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helios.HeliosService/GetFeatures',
            helios__pb2.GetFeaturesRequest.SerializeToString,
            helios__pb2.GetFeaturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIndicators(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helios.HeliosService/GetIndicators',
            helios__pb2.GetIndicatorsRequest.SerializeToString,
            helios__pb2.GetIndicatorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamOHLCV(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/helios.HeliosService/StreamOHLCV',
            helios__pb2.StreamOHLCVRequest.SerializeToString,
            helios__pb2.OHLCV.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/helios.HeliosService/StreamFeatures',
            helios__pb2.StreamFeaturesRequest.SerializeToString,
            helios__pb2.Feature.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamIndicators(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/helios.HeliosService/StreamIndicators',
            helios__pb2.StreamIndicatorsRequest.SerializeToString,
            helios__pb2.Indicator.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeToSymbols(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/helios.HeliosService/SubscribeToSymbols',
            helios__pb2.SubscriptionRequest.SerializeToString,
            helios__pb2.SubscriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
